name: Github Pages
on:
  push:
    branches:
      - source

jobs:
  build-deploy:
    runs-on: [ubuntu-18.04]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: yarn --non-interactive --frozen-lockfile install
      - name: Build
        run: yarn build
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./build
