name: Github Pages
on:
  push:
    branches:
      - source

jobs:
  build-deploy:
    runs-on: [ubuntu-18.04]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: yarn --non-interactive --frozen-lockfile install
      - name: Build
        run: yarn build
      - name: Publish to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.0
        with:
          dir: build
          branch: master
          token: ${{ secrets.ACCESS_TOKEN }}
