name: Github Pages
on:
  push:
    branches:
      - source

jobs:
  build-deploy:
    runs-on: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@master
      - name: Install
        run: yarn
      - name: Build & Deploy
        run: yarn deploy
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
