name: Github Pages
on:
  push:
    branches:
      - source

jobs:
  build-deploy:
    runs-on: [ubuntu-18.04]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: yarn --non-interactive --frozen-lockfile install
      - name: Build
        run: yarn build
      - name: Deploy
        uses: Cecilapp/GitHub-Pages-deploy@master
        env: 
          EMAIL: chrissalinasjr@gmail.com
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BUILD_DIR: build/
